"""add_relation_between_user_and_others_tables

Revision ID: 0444081ee118
Revises: dd10ce69928c
Create Date: 2026-07-14 23:35:52.583034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0444081ee118'
down_revision: Union[str, Sequence[str], None] = 'dd10ce69928c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_job', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'download_job', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('export_jobs', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'export_jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('playlists', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'playlists', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('tracks', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tracks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.drop_column('tracks', 'user_id')
    op.drop_constraint(None, 'playlists', type_='foreignkey')
    op.drop_column('playlists', 'user_id')
    op.drop_constraint(None, 'export_jobs', type_='foreignkey')
    op.drop_column('export_jobs', 'user_id')
    op.drop_constraint(None, 'download_job', type_='foreignkey')
    op.drop_column('download_job', 'user_id')
    # ### end Alembic commands ###
