"""add playlist color

Revision ID: 5fa949172667
Revises: b81b16625b23
Create Date: 2026-06-30 02:37:54.170607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa949172667'
down_revision: Union[str, Sequence[str], None] = 'b81b16625b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('color', sa.String(length=7), nullable=False, server_default="#6C63FF"))
    op.alter_column('playlists', 'color', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'color')
    # ### end Alembic commands ###
