"""fix_relationship_between_user_and_refresh_token

Revision ID: 76b5e9d2d8a5
Revises: 457d20c9d5c8
Create Date: 2026-07-14 15:39:05.490587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b5e9d2d8a5'
down_revision: Union[str, Sequence[str], None] = '457d20c9d5c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refresh_token_user_id_fkey'), 'refresh_token', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_token', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_token', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_token_user_id_fkey'), 'refresh_token', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
