"""add_field_payload_to_table_token

Revision ID: 7ce48ff2f518
Revises: e189acdc3832
Create Date: 2026-07-21 00:04:47.607325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce48ff2f518'
down_revision: Union[str, Sequence[str], None] = 'e189acdc3832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_tokens', sa.Column('payload', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_tokens', 'payload')
    # ### end Alembic commands ###
