"""add celery_task_id to download_job and export_job

Revision ID: 86ce2edfac38
Revises: e22ef3148270
Create Date: 2026-06-14 15:03:30.079339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ce2edfac38'
down_revision: Union[str, Sequence[str], None] = 'e22ef3148270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_job', sa.Column('celery_task_id', sa.Text(), nullable=True))
    op.add_column('export_jobs', sa.Column('celery_task_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export_jobs', 'celery_task_id')
    op.drop_column('download_job', 'celery_task_id')
    # ### end Alembic commands ###
