"""add_cascade_delete_between_playlist_and_export

Revision ID: 8d3a6e95326b
Revises: 4d57f3259835
Create Date: 2026-08-04 18:33:19.961750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3a6e95326b'
down_revision: Union[str, Sequence[str], None] = '4d57f3259835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('export_jobs_playlist_id_fkey'), 'export_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'export_jobs', 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'export_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('export_jobs_playlist_id_fkey'), 'export_jobs', 'playlists', ['playlist_id'], ['id'])
    # ### end Alembic commands ###
