"""fix_typo_in_table_refresh_token

Revision ID: ae6a723380f7
Revises: 76b5e9d2d8a5
Create Date: 2026-07-14 15:41:07.979786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6a723380f7'
down_revision: Union[str, Sequence[str], None] = '76b5e9d2d8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
