"""make_user_id_nullable_false

Revision ID: b0686f0c25f0
Revises: 0444081ee118
Create Date: 2026-07-15 00:30:15.671241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0686f0c25f0'
down_revision: Union[str, Sequence[str], None] = '0444081ee118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('download_job', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('export_jobs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('playlists', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tracks', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('playlists', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('export_jobs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('download_job', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
