"""fix_relation_between_playtlist_and_export

Revision ID: c9a4ff622c65
Revises: 8d3a6e95326b
Create Date: 2026-08-04 18:37:10.491279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a4ff622c65'
down_revision: Union[str, Sequence[str], None] = '8d3a6e95326b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
