"""fix_field_user_id_from_refresh_token_table

Revision ID: dd10ce69928c
Revises: ae6a723380f7
Create Date: 2026-07-14 19:55:31.253417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd10ce69928c'
down_revision: Union[str, Sequence[str], None] = 'ae6a723380f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'refresh_token', ['token_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_token', type_='unique')
    # ### end Alembic commands ###
