import type { Playlist, Track, QueueJob, LibraryStats } from "@/types";

export const MOCK_PLAYLISTS: Playlist[] = [
  {
    id: "pl-1",
    name: "Lofi Hip Hop Chill",
    description: "Relaxing beats to study and focus",
    color: "#6C63FF",
    trackCount: 24,
    createdAt: "2025-05-12T10:30:00Z",
    updatedAt: "2025-06-01T14:22:00Z",
    status: "active",
    totalDuration: 5820,
    completedTracks: 20,
    failedTracks: 1,
    pendingTracks: 3,
  },
  {
    id: "pl-2",
    name: "Brazilian Jazz Classics",
    description: "Tom Jobim, Chico Buarque e mais",
    color: "#FF6584",
    trackCount: 18,
    createdAt: "2025-04-28T08:15:00Z",
    updatedAt: "2025-05-30T09:10:00Z",
    status: "active",
    totalDuration: 4200,
    completedTracks: 18,
    failedTracks: 0,
    pendingTracks: 0,
  },
  {
    id: "pl-3",
    name: "Synthwave Retrowave",
    description: "80s inspired electronic music",
    color: "#43D9AD",
    trackCount: 31,
    createdAt: "2025-06-01T16:45:00Z",
    updatedAt: "2025-06-07T11:00:00Z",
    status: "active",
    totalDuration: 7380,
    completedTracks: 22,
    failedTracks: 2,
    pendingTracks: 7,
  },
  {
    id: "pl-4",
    name: "Indie Folk Discoveries",
    description: "Hidden gems and indie artists",
    color: "#F5A623",
    trackCount: 12,
    createdAt: "2025-05-20T12:00:00Z",
    updatedAt: "2025-06-05T18:30:00Z",
    status: "active",
    totalDuration: 2760,
    completedTracks: 10,
    failedTracks: 0,
    pendingTracks: 2,
  },
  {
    id: "pl-5",
    name: "Heavy Metal Anthology",
    description: "From Black Sabbath to modern metal",
    color: "#E74C3C",
    trackCount: 45,
    createdAt: "2025-03-10T09:00:00Z",
    updatedAt: "2025-05-15T21:00:00Z",
    status: "active",
    totalDuration: 11520,
    completedTracks: 45,
    failedTracks: 0,
    pendingTracks: 0,
  },
];

export const MOCK_TRACKS: Track[] = [
  {
    id: "tr-1",
    playlistId: "pl-1",
    playlistName: "Lofi Hip Hop Chill",
    name: "Midnight Study Session",
    artist: "ChilledCow",
    duration: 214,
    url: "https://youtube.com/watch?v=example1",
    status: "completed",
    addedAt: "2025-05-12T10:30:00Z",
    downloadedAt: "2025-05-12T10:45:00Z",
    fileSize: "5.2 MB",
    coverColor: "#6C63FF",
  },
  {
    id: "tr-2",
    playlistId: "pl-1",
    playlistName: "Lofi Hip Hop Chill",
    name: "Rain on Window",
    artist: "Lo-Fi Living",
    duration: 312,
    url: "https://youtube.com/watch?v=example2",
    status: "completed",
    addedAt: "2025-05-12T11:00:00Z",
    downloadedAt: "2025-05-12T11:12:00Z",
    fileSize: "7.8 MB",
    coverColor: "#4A90D9",
  },
  {
    id: "tr-3",
    playlistId: "pl-1",
    playlistName: "Lofi Hip Hop Chill",
    name: "Coffee Shop Vibes",
    artist: "Aesthetic Music",
    duration: 278,
    url: "https://youtube.com/watch?v=example3",
    status: "processing",
    addedAt: "2025-06-07T09:00:00Z",
    downloadedAt: null,
    fileSize: null,
    coverColor: "#E67E22",
    progress: 67,
  },
  {
    id: "tr-4",
    playlistId: "pl-1",
    playlistName: "Lofi Hip Hop Chill",
    name: "Nostalgia Haze",
    artist: "Dreamy Waves",
    duration: 0,
    url: "https://youtube.com/watch?v=example4",
    status: "failed",
    addedAt: "2025-06-06T14:00:00Z",
    downloadedAt: null,
    fileSize: null,
    coverColor: "#E74C3C",
    error: "URL inacessível ou conteúdo removido",
  },
  {
    id: "tr-5",
    playlistId: "pl-1",
    playlistName: "Lofi Hip Hop Chill",
    name: "Pixel Dream",
    artist: "8bit Lofi",
    duration: 0,
    url: "https://youtube.com/watch?v=example5",
    status: "pending",
    addedAt: "2025-06-08T08:00:00Z",
    downloadedAt: null,
    fileSize: null,
    coverColor: "#9B59B6",
  },
  {
    id: "tr-6",
    playlistId: "pl-2",
    playlistName: "Brazilian Jazz Classics",
    name: "Garota de Ipanema",
    artist: "Tom Jobim",
    duration: 252,
    url: "https://youtube.com/watch?v=example6",
    status: "completed",
    addedAt: "2025-04-28T08:15:00Z",
    downloadedAt: "2025-04-28T08:30:00Z",
    fileSize: "6.3 MB",
    coverColor: "#FF6584",
  },
  {
    id: "tr-7",
    playlistId: "pl-2",
    playlistName: "Brazilian Jazz Classics",
    name: "Águas de Março",
    artist: "Tom Jobim",
    duration: 180,
    url: "https://youtube.com/watch?v=example7",
    status: "completed",
    addedAt: "2025-04-28T08:45:00Z",
    downloadedAt: "2025-04-28T09:00:00Z",
    fileSize: "4.5 MB",
    coverColor: "#1ABC9C",
  },
  {
    id: "tr-8",
    playlistId: "pl-3",
    playlistName: "Synthwave Retrowave",
    name: "Neon Nights",
    artist: "Gunship",
    duration: 320,
    url: "https://youtube.com/watch?v=example8",
    status: "completed",
    addedAt: "2025-06-01T16:45:00Z",
    downloadedAt: "2025-06-01T17:00:00Z",
    fileSize: "8.0 MB",
    coverColor: "#43D9AD",
  },
  {
    id: "tr-9",
    playlistId: "pl-3",
    playlistName: "Synthwave Retrowave",
    name: "Turbo Killer",
    artist: "Carpenter Brut",
    duration: 392,
    url: "https://youtube.com/watch?v=example9",
    status: "processing",
    addedAt: "2025-06-08T07:30:00Z",
    downloadedAt: null,
    fileSize: null,
    coverColor: "#9B59B6",
    progress: 34,
  },
  {
    id: "tr-10",
    playlistId: "pl-5",
    playlistName: "Heavy Metal Anthology",
    name: "Iron Man",
    artist: "Black Sabbath",
    duration: 358,
    url: "https://youtube.com/watch?v=example10",
    status: "completed",
    addedAt: "2025-03-10T09:00:00Z",
    downloadedAt: "2025-03-10T09:15:00Z",
    fileSize: "8.9 MB",
    coverColor: "#E74C3C",
  },
];

export const MOCK_QUEUE: QueueJob[] = [
  { id: "job-1", trackName: "Coffee Shop Vibes", playlistName: "Lofi Hip Hop Chill", status: "processing", progress: 67, startedAt: "2025-06-08T09:00:00Z" },
  { id: "job-2", trackName: "Turbo Killer", playlistName: "Synthwave Retrowave", status: "processing", progress: 34, startedAt: "2025-06-08T09:05:00Z" },
  { id: "job-3", trackName: "Pixel Dream", playlistName: "Lofi Hip Hop Chill", status: "pending", progress: 0 },
  { id: "job-4", trackName: "Midnight City", playlistName: "Synthwave Retrowave", status: "pending", progress: 0 },
  { id: "job-5", trackName: "Autumn Leaves", playlistName: "Brazilian Jazz Classics", status: "pending", progress: 0 },
  { id: "job-6", trackName: "Nostalgia Haze", playlistName: "Lofi Hip Hop Chill", status: "failed", progress: 0, startedAt: "2025-06-06T14:00:00Z", error: "URL inacessível ou conteúdo removido" },
  { id: "job-7", trackName: "Garota de Ipanema", playlistName: "Brazilian Jazz Classics", status: "completed", progress: 100, startedAt: "2025-04-28T08:15:00Z", completedAt: "2025-04-28T08:30:00Z" },
  { id: "job-8", trackName: "Iron Man", playlistName: "Heavy Metal Anthology", status: "completed", progress: 100, startedAt: "2025-03-10T09:00:00Z", completedAt: "2025-03-10T09:15:00Z" },
];

export const MOCK_STATS: LibraryStats = {
  totalPlaylists: 5,
  totalTracks: 130,
  completedDownloads: 115,
  processingDownloads: 2,
  failedDownloads: 3,
  pendingDownloads: 10,
  storageUsedMb: 892,
  storageCapacityMb: 5120,
};
